# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: " "
email: Damans227@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
#baseurl: "" # the subpath of your site, e.g. /blog ***DISABLE THIS***

baseurl: "daemonsets"  #****ENABLE THIS****

#url: "http://daemonsets.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: Damans227/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#title: "DaemonSets.com"
logo: "/assets/images/DSLogo.png"

search: true

paginate: 5



author:
  name: "Daman Arora"
  avatar: "/assets/images/Damanarora.png"
  bio: "Hello World, <br /> I’m Daman. A highly motivated software developer pursuing Master of Engineering at **[Carleton University](https://carleton.ca/)**. I'm constantly seeking new, challenging, and exciting opportunities to improve my abilities. Please feel free to look around or find me on social media. <br />Thanks for visiting my site!" # Note: Markdown is allowed
  location: "Canada"
  links:
    - label: "Websites"
      icon: "fas fa-fw fa-link"
      url: "http://daemonsets.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DaemonSets"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Damans227"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/daman-arora-3679332a/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      show_date: true
    classes: wide



footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Damans227"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/daman-arora-3679332a/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DaemonSets"


plugins: #******ENABLE THIS*****
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

tag_archive:
  type: liquid
  path: /tags/
  

